import Head from "next/head";
import App from "./app";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wamtech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <App/>
    </>
  );
}
